### ISSUE TITLE
deck_name_in_title 2.1

### ISSUE THREAD

**Issue by khonkhortisan** [ospalh/anki-addons#117]
I added an `__init__.py` containing `from . import deck_name_in_title` and the three `.show = wrap(` lines at the bottom threw errors so I commented them out and it appears to work. It can't be this easy, right?

**Comment by ospalh** [comment]
Sure, it might be that simple.
I just haven’t gotten around to that one. I want to get some other add-ons to get working right before this one, and even for them, i don’t work hard on that.

Instead of using two files, one `__init__.py` and one, presumably still called `deck_name_in_title.py`, for simple add-ons like this i think it’s OK to put the real code into `<directory name>/__init__.py`. Even more simple than your change.

Anyway, i don’t see you having forked this repo, so, how do you want to go on? Publish the 2.1 add-on yourself? (I’m OK with that.) Do a fork and a pull request? Send the patch to me another way?

**Comment by khonkhortisan** [comment]
When it starts, the title is `Anki - User 1`. Clicking on a deck doesn't change the title, but showing a card does. `Clicked deck:-:deck::subdeck- Anki`. If I press s or d, the title stays the same. If by continuing to study I get to a card in a different subdeck, it changes. Looks like removing those three lines just broke the main view and deck view title resets. (I don't exactly remember how it behaved in 2.0, but I think that's right)
The right way to do this would be to keep the functions but change the calls to the new way. Just removing the lines makes the 2.0 version worse if the update ever trickles back.

**Comment by ospalh** [comment]
Sure, it might be that simple.
I just haven’t gotten around to that one. I want to get some other add-ons to get working right before this one, and even for them, i don’t work hard on that.

Instead of using two files, one `__init__.py` and one, presumably still called `deck_name_in_title.py`, for simple add-ons like this i think it’s OK to put the real code into `<directory name>/__init__.py`. Even more simple than your change.

Anyway, i don’t see you having forked this repo, so, how do you want to go on? Publish the 2.1 add-on yourself? (I’m OK with that.) Do a fork and a pull request? Send the patch to me another way?

**Comment by Arthur-Milchior** [comment]
Since your add-on now works with 2.1 and its a free software, I took the freedom to upload it on https://ankiweb.net/shared/info/699175524 so anyone can download it.
If one day you upload the add-on yourself, I'll delete this upload. Please let me know.
